### ISSUE TITLE
Docs: Getting Started Guides

### ISSUE THREAD

**Issue by MykalMachon** [MykalMachon/chat.mykal.codes#1]
## Summary of issue
I should create getting started guides for both the API and the WebApp that explain how to get them setup, how to interact with them, and some simple pointers on customizing them to work with your own blog / content source. 

## Todos
- [ ] Getting started guide for the WebApp
  - [ ] Basic step-by-step guide 
  - [ ] Customization tips 
- [ ] Getting started guide for the API
  - [ ] Basic step-by-step guide 
  - [ ] Customization tips
